(define (problem pb5)
    (:domain rpg)

    (:objects
        room_1 room_2 room_3 room_4 room_5
        room_6 room_7 room_8 room_9 room_10
        room_11 room_12 room_13 room_14 room_15
        room_16 room_17 room_18 room_19 room_20 - room
        hero_1 hero_2 - hero
    )

    (:init
        (hero_at hero_1 room_1)
        (goal_at hero_1 room_9)
        (hero_at hero_2 room_20)
        (goal_at hero_2 room_11)
        (empty_handed hero_1)
        (empty_handed hero_2)
        (monster_angry room_3)
        (monster_angry room_5)
        (monster_angry room_6)
        (monster_angry room_8)
        (monster_angry room_13)
        (monster_angry room_14)
        (monster_angry room_15)
        (monster_angry room_16)
        (monster_angry room_17)
        (sword_at room_2)
        (sword_at room_4)
        (sword_at room_18)
        (trap_armed room_10)
        (trap_armed room_12)
        (valid_move room_1 room_2)
        (valid_move room_1 room_6)
        (valid_move room_2 room_3)
        ; (valid_move room_2 room_7)
        (valid_move room_2 room_1)
        (valid_move room_3 room_4)
        (valid_move room_3 room_8)
        (valid_move room_3 room_2)
        (valid_move room_4 room_5)
        (valid_move room_4 room_9)
        (valid_move room_4 room_3)
        (valid_move room_5 room_10)
        (valid_move room_5 room_4)
        (valid_move room_6 room_1)
        ; (valid_move room_6 room_7)
        (valid_move room_6 room_11)
        ; (valid_move room_7 room_2)
        ; (valid_move room_7 room_8)
        ; (valid_move room_7 room_12)
        ; (valid_move room_7 room_6)
        (valid_move room_8 room_3)
        (valid_move room_8 room_9)
        (valid_move room_8 room_13)
        ; (valid_move room_8 room_7)
        (valid_move room_9 room_4)
        (valid_move room_9 room_10)
        (valid_move room_9 room_14)
        (valid_move room_9 room_8)
        (valid_move room_10 room_5)
        (valid_move room_10 room_15)
        (valid_move room_10 room_9)
        (valid_move room_11 room_6)
        (valid_move room_11 room_12)
        (valid_move room_11 room_16)
        ; (valid_move room_12 room_7)
        (valid_move room_12 room_13)
        (valid_move room_12 room_17)
        (valid_move room_12 room_11)
        (valid_move room_13 room_8)
        (valid_move room_13 room_14)
        (valid_move room_13 room_18)
        (valid_move room_13 room_12)
        (valid_move room_14 room_9)
        (valid_move room_14 room_15)
        (valid_move room_14 room_19)
        (valid_move room_14 room_13)
        (valid_move room_15 room_10)
        (valid_move room_15 room_20)
        (valid_move room_15 room_14)
        (valid_move room_16 room_11)
        (valid_move room_16 room_17)
        (valid_move room_17 room_12)
        (valid_move room_17 room_18)
        (valid_move room_17 room_16)
        (valid_move room_18 room_13)
        (valid_move room_18 room_19)
        (valid_move room_18 room_17)
        (valid_move room_19 room_14)
        (valid_move room_19 room_20)
        (valid_move room_19 room_18)
        (valid_move room_20 room_15)
        (valid_move room_20 room_19)
    )

    (:goal (and
        (hero_at hero_1 room_9)
        (hero_at hero_2 room_11)
    ))
)